//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSDL.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://danateq.com/cmp/soap/", ConfigurationName="ServiceReference.RetailerGetOffers")]
    public interface RetailerGetOffers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://danateq.com/cmp/soap/RetailerGetOffers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSDL.ServiceReference.RetailerGetOffersResponse1 RetailerGetOffers(WSDL.ServiceReference.RetailerGetOffersRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://danateq.com/cmp/soap/RetailerGetOffers", ReplyAction="*")]
        System.Threading.Tasks.Task<WSDL.ServiceReference.RetailerGetOffersResponse1> RetailerGetOffersAsync(WSDL.ServiceReference.RetailerGetOffersRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://danateq.com/cmp/soap/")]
    public partial class RetailerGetOffersRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string retailerMSISDNField;
        
        private string customerMSISDNField;
        
        private uint rechargeAmountField;
        
        private uint offersCountLimitField;
        
        private string transactionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RetailerMSISDN {
            get {
                return this.retailerMSISDNField;
            }
            set {
                this.retailerMSISDNField = value;
                this.RaisePropertyChanged("RetailerMSISDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CustomerMSISDN {
            get {
                return this.customerMSISDNField;
            }
            set {
                this.customerMSISDNField = value;
                this.RaisePropertyChanged("CustomerMSISDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public uint RechargeAmount {
            get {
                return this.rechargeAmountField;
            }
            set {
                this.rechargeAmountField = value;
                this.RaisePropertyChanged("RechargeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public uint OffersCountLimit {
            get {
                return this.offersCountLimitField;
            }
            set {
                this.offersCountLimitField = value;
                this.RaisePropertyChanged("OffersCountLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://danateq.com/cmp/soap/")]
    public partial class Offer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong offerIDField;
        
        private string offerDescrField;
        
        private string offerCorrIDField;
        
        private int offerPriorityField;
        
        private string[] offerCategoryField;
        
        private string retailerCommissionField;
        
        private string optInKeywordField;
        
        private ulong campaignIDField;
        
        private bool campaignIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ulong OfferID {
            get {
                return this.offerIDField;
            }
            set {
                this.offerIDField = value;
                this.RaisePropertyChanged("OfferID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OfferDescr {
            get {
                return this.offerDescrField;
            }
            set {
                this.offerDescrField = value;
                this.RaisePropertyChanged("OfferDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OfferCorrID {
            get {
                return this.offerCorrIDField;
            }
            set {
                this.offerCorrIDField = value;
                this.RaisePropertyChanged("OfferCorrID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int OfferPriority {
            get {
                return this.offerPriorityField;
            }
            set {
                this.offerPriorityField = value;
                this.RaisePropertyChanged("OfferPriority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OfferCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string[] OfferCategory {
            get {
                return this.offerCategoryField;
            }
            set {
                this.offerCategoryField = value;
                this.RaisePropertyChanged("OfferCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string RetailerCommission {
            get {
                return this.retailerCommissionField;
            }
            set {
                this.retailerCommissionField = value;
                this.RaisePropertyChanged("RetailerCommission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string OptInKeyword {
            get {
                return this.optInKeywordField;
            }
            set {
                this.optInKeywordField = value;
                this.RaisePropertyChanged("OptInKeyword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ulong CampaignID {
            get {
                return this.campaignIDField;
            }
            set {
                this.campaignIDField = value;
                this.RaisePropertyChanged("CampaignID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CampaignIDSpecified {
            get {
                return this.campaignIDFieldSpecified;
            }
            set {
                this.campaignIDFieldSpecified = value;
                this.RaisePropertyChanged("CampaignIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://danateq.com/cmp/soap/")]
    public partial class RetailerGetOffersResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private uint operationStatusField;
        
        private Offer[] recommendedOffersField;
        
        private string sessionContextField;
        
        private string transactionIDField;
        
        private string offersCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public uint OperationStatus {
            get {
                return this.operationStatusField;
            }
            set {
                this.operationStatusField = value;
                this.RaisePropertyChanged("OperationStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Offer[] RecommendedOffers {
            get {
                return this.recommendedOffersField;
            }
            set {
                this.recommendedOffersField = value;
                this.RaisePropertyChanged("RecommendedOffers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SessionContext {
            get {
                return this.sessionContextField;
            }
            set {
                this.sessionContextField = value;
                this.RaisePropertyChanged("SessionContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string OffersCount {
            get {
                return this.offersCountField;
            }
            set {
                this.offersCountField = value;
                this.RaisePropertyChanged("OffersCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetailerGetOffersRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://danateq.com/cmp/soap/", Order=0)]
        public WSDL.ServiceReference.RetailerGetOffersRequest RetailerGetOffersRequest;
        
        public RetailerGetOffersRequest1() {
        }
        
        public RetailerGetOffersRequest1(WSDL.ServiceReference.RetailerGetOffersRequest RetailerGetOffersRequest) {
            this.RetailerGetOffersRequest = RetailerGetOffersRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetailerGetOffersResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://danateq.com/cmp/soap/", Order=0)]
        public WSDL.ServiceReference.RetailerGetOffersResponse RetailerGetOffersResponse;
        
        public RetailerGetOffersResponse1() {
        }
        
        public RetailerGetOffersResponse1(WSDL.ServiceReference.RetailerGetOffersResponse RetailerGetOffersResponse) {
            this.RetailerGetOffersResponse = RetailerGetOffersResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RetailerGetOffersChannel : WSDL.ServiceReference.RetailerGetOffers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetailerGetOffersClient : System.ServiceModel.ClientBase<WSDL.ServiceReference.RetailerGetOffers>, WSDL.ServiceReference.RetailerGetOffers {
        
        public RetailerGetOffersClient() {
        }
        
        public RetailerGetOffersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetailerGetOffersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetailerGetOffersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetailerGetOffersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WSDL.ServiceReference.RetailerGetOffersResponse1 RetailerGetOffers(WSDL.ServiceReference.RetailerGetOffersRequest1 request) {
            return base.Channel.RetailerGetOffers(request);
        }
        
        public System.Threading.Tasks.Task<WSDL.ServiceReference.RetailerGetOffersResponse1> RetailerGetOffersAsync(WSDL.ServiceReference.RetailerGetOffersRequest1 request) {
            return base.Channel.RetailerGetOffersAsync(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://danateq.com/cmp/soap/", ConfigurationName="ServiceReference.RetailerOptIn")]
    public interface RetailerOptIn {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://danateq.com/cmp/soap/RetailerOptIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSDL.ServiceReference.RetailerOptInResponse1 RetailerOptIn(WSDL.ServiceReference.RetailerOptInRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://danateq.com/cmp/soap/RetailerOptIn", ReplyAction="*")]
        System.Threading.Tasks.Task<WSDL.ServiceReference.RetailerOptInResponse1> RetailerOptInAsync(WSDL.ServiceReference.RetailerOptInRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://danateq.com/cmp/soap/")]
    public partial class RetailerOptInRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string retailerMSISDNField;
        
        private string customerMSISDNField;
        
        private string optInKeywordField;
        
        private string offerCorrIDField;
        
        private ulong offerIDField;
        
        private ulong campaignIDField;
        
        private bool campaignIDFieldSpecified;
        
        private string pINField;
        
        private string sessionContextField;
        
        private string transactionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RetailerMSISDN {
            get {
                return this.retailerMSISDNField;
            }
            set {
                this.retailerMSISDNField = value;
                this.RaisePropertyChanged("RetailerMSISDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CustomerMSISDN {
            get {
                return this.customerMSISDNField;
            }
            set {
                this.customerMSISDNField = value;
                this.RaisePropertyChanged("CustomerMSISDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OptInKeyword {
            get {
                return this.optInKeywordField;
            }
            set {
                this.optInKeywordField = value;
                this.RaisePropertyChanged("OptInKeyword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OfferCorrID {
            get {
                return this.offerCorrIDField;
            }
            set {
                this.offerCorrIDField = value;
                this.RaisePropertyChanged("OfferCorrID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ulong OfferID {
            get {
                return this.offerIDField;
            }
            set {
                this.offerIDField = value;
                this.RaisePropertyChanged("OfferID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ulong CampaignID {
            get {
                return this.campaignIDField;
            }
            set {
                this.campaignIDField = value;
                this.RaisePropertyChanged("CampaignID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CampaignIDSpecified {
            get {
                return this.campaignIDFieldSpecified;
            }
            set {
                this.campaignIDFieldSpecified = value;
                this.RaisePropertyChanged("CampaignIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PIN {
            get {
                return this.pINField;
            }
            set {
                this.pINField = value;
                this.RaisePropertyChanged("PIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SessionContext {
            get {
                return this.sessionContextField;
            }
            set {
                this.sessionContextField = value;
                this.RaisePropertyChanged("SessionContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://danateq.com/cmp/soap/")]
    public partial class RetailerOptInResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private uint operationStatusField;
        
        private string transactionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public uint OperationStatus {
            get {
                return this.operationStatusField;
            }
            set {
                this.operationStatusField = value;
                this.RaisePropertyChanged("OperationStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetailerOptInRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://danateq.com/cmp/soap/", Order=0)]
        public WSDL.ServiceReference.RetailerOptInRequest RetailerOptInRequest;
        
        public RetailerOptInRequest1() {
        }
        
        public RetailerOptInRequest1(WSDL.ServiceReference.RetailerOptInRequest RetailerOptInRequest) {
            this.RetailerOptInRequest = RetailerOptInRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetailerOptInResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://danateq.com/cmp/soap/", Order=0)]
        public WSDL.ServiceReference.RetailerOptInResponse RetailerOptInResponse;
        
        public RetailerOptInResponse1() {
        }
        
        public RetailerOptInResponse1(WSDL.ServiceReference.RetailerOptInResponse RetailerOptInResponse) {
            this.RetailerOptInResponse = RetailerOptInResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RetailerOptInChannel : WSDL.ServiceReference.RetailerOptIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetailerOptInClient : System.ServiceModel.ClientBase<WSDL.ServiceReference.RetailerOptIn>, WSDL.ServiceReference.RetailerOptIn {
        
        public RetailerOptInClient() {
        }
        
        public RetailerOptInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetailerOptInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetailerOptInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetailerOptInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WSDL.ServiceReference.RetailerOptInResponse1 RetailerOptIn(WSDL.ServiceReference.RetailerOptInRequest1 request) {
            return base.Channel.RetailerOptIn(request);
        }
        
        public System.Threading.Tasks.Task<WSDL.ServiceReference.RetailerOptInResponse1> RetailerOptInAsync(WSDL.ServiceReference.RetailerOptInRequest1 request) {
            return base.Channel.RetailerOptInAsync(request);
        }
    }
}
